# Generated by Django 5.2 on 2025-07-01 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='group',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='type',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='missionlist',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='missionlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='evo_pet',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='type',
        ),
        migrations.RemoveField(
            model_name='petlist',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='petlist',
            name='user',
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('CEO', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('fax', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('founder', models.TextField(blank=True, null=True)),
                ('founded', models.TextField(blank=True, null=True)),
                ('authority', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('focus', models.TextField(blank=True, null=True)),
                ('minAge', models.TextField(blank=True, null=True)),
                ('maxAge', models.TextField(blank=True, null=True)),
                ('service', models.TextField(blank=True, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.eventtype')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.servicegender')),
            ],
        ),
        migrations.CreateModel(
            name='CharityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.location')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ItemGroup',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemList',
        ),
        migrations.DeleteModel(
            name='MissionGroup',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='MissionList',
        ),
        migrations.DeleteModel(
            name='PetType',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='PetList',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
