# Generated by Django 5.2.4 on 2025-07-31 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='EventParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joinType', models.CharField(choices=[('Join', 'Join'), ('Save', 'Save')], default='Join', max_length=20)),
                ('charityEvent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.charityevent')),
                ('personalUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
