# Generated by Django 5.2.3 on 2025-08-04 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_charityevent_participants_eventparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charityevent',
            name='online',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QRCodeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('expireTime', models.DateTimeField()),
                ('isUsed', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('charityEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.charityevent')),
                ('personalUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
