# Generated by Django 5.2 on 2025-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_eventtype_location_servicegender_remove_item_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='area',
            field=models.ManyToManyField(to='backend.location'),
        ),
    ]
