# Generated by Django 5.2.4 on 2025-08-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_charityevent_online_qrcoderecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcoderecord',
            name='charityEvent',
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Save', 'Save'), ('Join', 'Join')], default='Join', max_length=20),
        ),
    ]
