# Generated by Django 5.2 on 2025-07-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_organization_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='area',
            field=models.ManyToManyField(blank=True, null=True, to='backend.location'),
        ),
    ]
