# Generated by Django 5.2 on 2025-07-03 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_charityinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='eventType',
            field=models.ManyToManyField(blank=True, to='backend.eventtype'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.location'),
        ),
    ]
