# Generated by Django 5.2.3 on 2025-08-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_prize_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='sender',
        ),
        migrations.AddField(
            model_name='letter',
            name='charityEvent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='backend.charityevent'),
        ),
        migrations.AddField(
            model_name='letter',
            name='officialEvent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='backend.officialevent'),
        ),
        migrations.AddField(
            model_name='reward',
            name='isReceived',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LetterExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templateName', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.lettertype')),
            ],
        ),
    ]
