# Generated by Django 5.2 on 2025-07-03 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_personalinfo_eventtype_personalinfo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityinfo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityinfo',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityinfo',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.eventtype'),
        ),
        migrations.DeleteModel(
            name='OrganizationArea',
        ),
    ]
