# Generated by Django 5.2.3 on 2025-08-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_letter_sender_letter_charityevent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prize',
            new_name='PrizeType',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='isReceived',
        ),
        migrations.AddField(
            model_name='charityevent',
            name='isCanvass',
            field=models.BooleanField(default=False),
        ),
    ]
