# Generated by Django 5.2.4 on 2025-08-27 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_prize_prizetype_remove_reward_isreceived_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='charityeventcoorganizer',
            table='backend_charityevent_coOrganizer',
        ),
    ]
