# Generated by Django 5.2.4 on 2025-07-18 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_location_latitude_location_longitude_charityevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Normal', 'Normal'), ('Casino', 'Casino')], default='Normal', max_length=20)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='charityevent',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OfficialEventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betAmount', models.IntegerField()),
                ('officialEvent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.officialevent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='officialevent',
            name='participants',
            field=models.ManyToManyField(related_name='officialEvents', through='backend.OfficialEventParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
