# Generated by Django 5.2.4 on 2025-08-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_charityeventcoorganizer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Join', 'Join'), ('Save', 'Save')], default='Join', max_length=20),
        ),
    ]
