# Generated by Django 5.2.4 on 2025-07-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_officialevent_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialevent',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officialevent',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
