# Generated by Django 5.2 on 2025-08-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_eventparticipant_jointype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Save', 'Save'), ('Join', 'Join')], default='Join', max_length=20),
        ),
    ]
