# Generated by Django 5.2.3 on 2025-09-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_eventparticipant_jointype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charityevent',
            name='isCanvass',
        ),
        migrations.RemoveField(
            model_name='charityevent',
            name='recommendedBy',
        ),
        migrations.AlterField(
            model_name='charityevent',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Save', 'Save'), ('Join', 'Join')], default='Join', max_length=20),
        ),
    ]
