# Generated by Django 5.2.3 on 2025-09-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_charityevent_iscanvass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityevent',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Join', 'Join'), ('Save', 'Save')], default='Join', max_length=20),
        ),
    ]
