# Generated by Django 5.2.4 on 2025-09-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_eventparticipant_jointype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Join', 'Join'), ('Save', 'Save')], default='Join', max_length=20),
        ),
        migrations.CreateModel(
            name='ItemBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('prizeType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.prize')),
            ],
        ),
        migrations.AlterField(
            model_name='reward',
            name='prize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.prize'),
        ),
        migrations.DeleteModel(
            name='LetterExample',
        ),
        migrations.DeleteModel(
            name='PrizeType',
        ),
    ]
