# Generated by Django 5.2.4 on 2025-09-11 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_prize_alter_eventparticipant_jointype_itembox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembox',
            name='personalInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.personalinfo'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Save', 'Save'), ('Join', 'Join')], default='Join', max_length=20),
        ),
    ]
