# Generated by Django 5.2.4 on 2025-09-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_itembox_personalinfo_alter_eventparticipant_jointype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itembox',
            old_name='prizeType',
            new_name='prize',
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Join', 'Join'), ('Save', 'Save')], default='Join', max_length=20),
        ),
    ]
