# Generated by Django 5.2 on 2025-09-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_rename_prizetype_itembox_prize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityevent',
            name='status',
            field=models.CharField(blank=True, choices=[('upcoming', 'upcoming'), ('ongoing', 'ongoing'), ('finished', 'finished'), ('unknown', 'unknown')], default='unknown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Save', 'Save'), ('Finished', 'Finished'), ('Join', 'Join')], default='Join', max_length=20),
        ),
    ]
