# Generated by Django 5.2.3 on 2025-09-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_charityevent_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Save', 'Save'), ('Join', 'Join'), ('Finished', 'Finished')], default='Join', max_length=20),
        ),
    ]
