# Generated by Django 5.2.4 on 2025-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_charityevent_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Save', 'Save'), ('Join', 'Join')], default='Join', max_length=20),
        ),
    ]
