# Generated by Django 5.2 on 2025-09-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_eventparticipant_jointype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Join', 'Join'), ('Save', 'Save'), ('Finished', 'Finished')], default='Join', max_length=20),
        ),
    ]
