# Generated by Django 5.2.4 on 2025-09-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_eventparticipant_jointype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Join', 'Join'), ('Finished', 'Finished'), ('Save', 'Save')], default='Join', max_length=20),
        ),
    ]
