# Generated by Django 5.2.6 on 2025-09-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_eventparticipant_jointype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityevent',
            name='status',
            field=models.CharField(blank=True, choices=[('upcoming', 'upcoming'), ('ongoing', 'ongoing'), ('finished', 'finished'), ('deleted', 'deleted'), ('unknown', 'unknown')], default='unknown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Join', 'Join'), ('Save', 'Save')], default='Join', max_length=20),
        ),
    ]
