# Generated by Django 5.2.4 on 2025-09-26 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_charityevent_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Octopus', 'Octopus'), ('Slime', 'Slime'), ('Blood', 'Blood'), ('Bear', 'Bear'), ('Turtle', 'Turtle'), ('Rice', 'Rice'), ('Whole', 'Whole')], default='Whole', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Cash', 'Cash'), ('Powerup', 'Item')], default='Cash', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='itembox',
            name='prize',
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Join', 'Join'), ('Finished', 'Finished'), ('Save', 'Save')], default='Join', max_length=20),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=20)),
                ('point', models.IntegerField()),
                ('itemAttribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.attribute')),
                ('itemType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.itemtype')),
            ],
        ),
        migrations.AddField(
            model_name='itembox',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.item'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='prize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.item'),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fullPoint', models.IntegerField()),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentPoint', models.IntegerField()),
                ('personalInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.personalinfo')),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.pet')),
            ],
        ),
        migrations.DeleteModel(
            name='Prize',
        ),
    ]
