# Generated by Django 5.2.4 on 2025-09-26 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_attribute_itemtype_remove_itembox_prize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Save', 'Save'), ('Finished', 'Finished'), ('Join', 'Join')], default='Join', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemAttribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.attribute'),
        ),
        migrations.AlterField(
            model_name='item',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
