# Generated by Django 5.2.4 on 2025-09-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_eventparticipant_jointype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Join', 'Join'), ('Finished', 'Finished'), ('Save', 'Save')], default='Join', max_length=20),
        ),
    ]
