# Generated by Django 5.2.4 on 2025-09-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_pet_description_alter_eventparticipant_jointype'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemImage',
            field=models.ImageField(blank=True, null=True, upload_to='powerup/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='itemImage',
            field=models.ImageField(blank=True, null=True, upload_to='pet/'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Save', 'Save'), ('Finished', 'Finished'), ('Join', 'Join')], default='Join', max_length=20),
        ),
    ]
