# Generated by Django 5.2.4 on 2025-10-02 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_item_itemimage_pet_itemimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='prize',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='officialEvent',
        ),
        migrations.AddField(
            model_name='letter',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.reward'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Join', 'Join'), ('Finished', 'Finished'), ('Save', 'Save')], default='Join', max_length=20),
        ),
    ]
