# Generated by Django 5.2 on 2025-10-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_eventparticipant_jointype'),
        ('backend', '0028_item_itemimage_pet_itemimage_and_more'),
    ]

    operations = [
    ]
