# Generated by Django 5.2.4 on 2025-10-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_merge_20251002_2342'),
        ('backend', '0029_rename_prize_reward_item_remove_letter_officialevent_and_more'),
    ]

    operations = [
    ]
