# Generated by Django 5.2.4 on 2025-10-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_merge_20251003_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='probability',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(choices=[('Join', 'Join'), ('Save', 'Save'), ('Finished', 'Finished')], default='Join', max_length=20),
        ),
    ]
