# Generated by Django 5.2.4 on 2025-10-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_pet_probability_alter_eventparticipant_jointype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(blank=True, choices=[('Join', 'Join'), ('Finished', 'Finished'), ('Save', 'Save')], default='Join', max_length=20, null=True),
        ),
    ]
