# Generated by Django 5.2.4 on 2025-11-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_eventparticipant_jointype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(blank=True, choices=[('Join', 'Join'), ('Save', 'Save'), ('Finished', 'Finished')], default='Join', max_length=20, null=True),
        ),
    ]
