# Generated by Django 5.2 on 2025-11-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_alter_eventparticipant_jointype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(blank=True, choices=[('Save', 'Save'), ('Join', 'Join'), ('Finished', 'Finished')], default='Join', max_length=20, null=True),
        ),
    ]
