# Generated by Django 5.2 on 2025-11-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_alter_eventparticipant_jointype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='joinType',
            field=models.CharField(blank=True, choices=[('Save', 'Save'), ('Finished', 'Finished'), ('Join', 'Join')], default='Join', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='qrcoderecord',
            name='expireTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
